
---
AWSTemplateFormatVersion: '2010-09-09'
# Creates a database. The metadata created in the Data Catalog points to the flights public S3 bucket
Parameters:
  CFNDatabaseName:
    Type: String
    Default: tpc

# Resources section defines metadata for the Data Catalog
Resources:
# Create an AWS Glue database
  CFNDatabaseFlights:
    Type: AWS::Glue::Database
    Properties:
      # The database is created in the Data Catalog for your account
      CatalogId: !Ref AWS::AccountId   
      DatabaseInput:
        # The name of the database is defined in the Parameters section above
        Name: !Ref CFNDatabaseName
        Description: Database to hold tables for flights data
        LocationUri: s3://crawler-public-us-east-1/flight/2016/csv/
        LocationUri:  !Join 
            - '-'
            - - s3://lf-data-lake
              - !Ref 'AWS::AccountId'
        #Parameters: Leave AWS database parameters blank
  LFPermissionsForGlueCrawler:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties: 
      Catalog: !Ref AWS::AccountId
      Permissions: 
        - "CREATE_TABLE" 
        - "ALTER" 
        - "DROP" 
        - "DESCRIBE"
      PermissionsWithGrantOption: 
        - "CREATE_TABLE" 
        - "ALTER" 
        - "DROP" 
        - "DESCRIBE"
      Principal: 
        DataLakePrincipalIdentifier: "arn:aws:iam::555344254085:role/LF-GlueServiceRole"
      Resource: 
        Database:
          CatalogId: !Ref AWS::AccountId
          Name: !Ref CFNDatabaseFlights
