Description: Assign permissions to alter table to add LF-Tags
Parameters:
  CFNDatabaseName:
    Type: String
    Default: tpc
  DataAdminName:
    Type: String
    Default: lf-data-admin
Resources:
 #Add the ALTER permission to the preexisting permissions for the dl_tpc_customer table
  LFTagsPermissionsForTable:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties: 
      Catalog: !Ref AWS::AccountId
      Permissions:  
        - "ALTER" 
      PermissionsWithGrantOption:  
        - "ALTER" 
      Principal: 
        DataLakePrincipalIdentifier: !Sub "arn:aws:iam::${AWS::AccountId}:user/${DataAdminName}"
      Resource: 
        Table:
          CatalogId: !Ref AWS::AccountId
          DatabaseName: !Ref CFNDatabaseName
          Name: "dl_tpc_customer"