Description: Associate a user with a Lake Formation tag
Parameters:
  GroupVal3:
    Type: String
    Default: analyst
  DataAdminName:
    Type: String
    Default: lf-data-admin
Resources:
  TagPermission:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties: 
      Principal:
        DataLakePrincipalIdentifier: !Sub "arn:aws:iam::${AWS::AccountId}:user/${DataAdminName}"
      Permissions: 
        - ASSOCIATE
        - DESCRIBE
      PermissionsWithGrantOption:
        - ASSOCIATE
        - DESCRIBE
      Resource: 
        LFTag:
          CatalogId: !Ref AWS::AccountId
          TagKey: "group"
          TagValues:
              - !Ref GroupVal3